dist: appease hackage tar requirements
Hackage requires all filenames in tar archives to be valid on both
POSIX and Windows (see below error message during `cabal upload')

  Error: Invalid package

  Invalid windows file name in tar archive:
  "purebred-0.1.0.0\\test\\data\\Maildir\\cur\\1502418188.M630889P26155V000000000000FD03I0000000000A23153.url:2,RS".
  For portability, hackage requires that file names be valid on both Unix and
  Windows systems, and not refer outside of the tarball.

Change the name of the file with the colon to appease hackage.
Also update the UAT suite to fix up the filenames when creating
the Maildir.